// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR3KdL9YRC6xsj_uUclTP450WwqXxRhV4',
    appId: '1:893826836090:web:5b6258d1ce2a3cf2d1fdc3',
    messagingSenderId: '893826836090',
    projectId: 'testing-aa21c',
    authDomain: 'testing-aa21c.firebaseapp.com',
    databaseURL: 'https://testing-aa21c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testing-aa21c.appspot.com',
    measurementId: 'G-ZKMC5YK94D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKsAaz-dMfAldT6JI0UMfPbjd-Tq4yeEQ',
    appId: '1:893826836090:android:c1ef203001ba6888d1fdc3',
    messagingSenderId: '893826836090',
    projectId: 'testing-aa21c',
    databaseURL: 'https://testing-aa21c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testing-aa21c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHfe2CPWVcygUVFFWUHHE_TIdsR13JVas',
    appId: '1:893826836090:ios:cb1bbefbc84c67c6d1fdc3',
    messagingSenderId: '893826836090',
    projectId: 'testing-aa21c',
    databaseURL: 'https://testing-aa21c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testing-aa21c.appspot.com',
    androidClientId: '893826836090-0rrm1thltaaiqk9i476l6pm96mff7mjc.apps.googleusercontent.com',
    iosClientId: '893826836090-nro1ilqq4qgpie0u7njn959v2rmo1cfr.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHfe2CPWVcygUVFFWUHHE_TIdsR13JVas',
    appId: '1:893826836090:ios:77c29c5a57448e3ed1fdc3',
    messagingSenderId: '893826836090',
    projectId: 'testing-aa21c',
    databaseURL: 'https://testing-aa21c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testing-aa21c.appspot.com',
    androidClientId: '893826836090-0rrm1thltaaiqk9i476l6pm96mff7mjc.apps.googleusercontent.com',
    iosClientId: '893826836090-pfdekpb282tpjmsnf98021sn8ootfovs.apps.googleusercontent.com',
    iosBundleId: 'com.DN.notes',
  );
}
